// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNz0NeDFubxMf4Y_gubluWBsTUQxycvpc',
    appId: '1:1032598054781:web:058283375ae715505b4e14',
    messagingSenderId: '1032598054781',
    projectId: 'warehousemanagement-20658',
    authDomain: 'warehousemanagement-20658.firebaseapp.com',
    storageBucket: 'warehousemanagement-20658.firebasestorage.app',
    measurementId: 'G-9E0TNNVSDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TSi9LyYcIryjaHMssMPiTFBsoR2h16o',
    appId: '1:1032598054781:android:36b99caefbae0e055b4e14',
    messagingSenderId: '1032598054781',
    projectId: 'warehousemanagement-20658',
    storageBucket: 'warehousemanagement-20658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMaHz0c3kA5ECijklmhCyqAp0dnqkU1c4',
    appId: '1:1032598054781:ios:917f8dd72539a16d5b4e14',
    messagingSenderId: '1032598054781',
    projectId: 'warehousemanagement-20658',
    storageBucket: 'warehousemanagement-20658.firebasestorage.app',
    iosBundleId: 'com.example.warehousemanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMaHz0c3kA5ECijklmhCyqAp0dnqkU1c4',
    appId: '1:1032598054781:ios:917f8dd72539a16d5b4e14',
    messagingSenderId: '1032598054781',
    projectId: 'warehousemanagement-20658',
    storageBucket: 'warehousemanagement-20658.firebasestorage.app',
    iosBundleId: 'com.example.warehousemanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNz0NeDFubxMf4Y_gubluWBsTUQxycvpc',
    appId: '1:1032598054781:web:2b462a1d92e642a45b4e14',
    messagingSenderId: '1032598054781',
    projectId: 'warehousemanagement-20658',
    authDomain: 'warehousemanagement-20658.firebaseapp.com',
    storageBucket: 'warehousemanagement-20658.firebasestorage.app',
    measurementId: 'G-NYV26LM9YH',
  );
}
